# Generated by Django 4.2.11 on 2024-04-07 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='master_order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='response_order_enum',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='trans_date_time',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_for_orders', to='order_items.orderitems'),
        ),
    ]
