# Generated by Django 4.2.11 on 2024-04-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='response_order_enum',
        ),
    ]
